/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "FlockAccounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FlockApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "FlockItems": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FlockSyncMessages": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PushNotificationsDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PushNotificationsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VAPID_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VAPID_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VAPID_SUBJECT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VaultApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "VaultMigrations": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}