/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "FlockAccounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FlockApp": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "FlockItems": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "FlockSubscriptions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "VaultApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "VaultMigrations": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}