describe('create account', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
    cy.createAccount('wellthisisverysecureisn\'tit?')
  })

  it('apply default maturity levels and edit maturity settings', () => {
    cy.createPerson({ firstName: 'Frodo', lastName: 'Baggins' })
    cy.dataCy('maturity-selection')
      .click()
    cy.contains(/non-Christian/i)
      .click()
      .saveDrawer()
    cy.dataCy('page-settings').click()
    cy.dataCy('maturity-stages')
      .find('[data-cy=edit-button]')
      .click()

    // Check order swapping
    cy.dataCy('maturity-move-up').first()
      .should('be.disabled')
    cy.dataCy('maturity-move-down').last()
      .should('be.disabled')
    cy.dataCy('maturity-move-down').eq(1)
      .click()
    cy.dataCy('maturity-move-up').eq(1)
      .click()
    cy.dataCy('maturity-stage-name').find('input').first()
      .should('have.value', 'Mature Christian')
    cy.dataCy('maturity-stage-name').find('input').last()
      .should('have.value', 'Young Christian')

    // Remove, add, and edit some stages
    cy.dataCy('maturity-remove-stage')
      .eq(1).click()
    cy.dataCy('maturity-add-stage').click()
    cy.dataCy('maturity-stage-name').last()
      .find('input').should('be.focused')
      .type('Partner')
    cy.dataCy('maturity-stage-name').first()
      .clear()
      .type('Attended')
    cy.dataCy('maturity-stage-name').eq(1)
      .clear()
      .type('Regular')
    cy.dataCy('maturity-done').click()
    cy.dataCy('page-content').contains('Christian').should('not.exist')
    cy.dataCy('page-content').find('[data-cy=tag]').as('stages')
    cy.get('@stages').eq(0).contains('Attended')
    cy.get('@stages').eq(1).contains('Regular')
    cy.get('@stages').eq(2).contains('Partner')

    // Previous maturity selection should not exist
    cy.dataCy('page-people').click()
    cy.contains('Frodo').click()
    cy.dataCy('maturity-selection').find('input').should('have.value', '')

    // Choose one of the new maturity values
    cy.dataCy('maturity-selection').click()
    cy.contains('Non-Christian').should('not.exist')
    cy.contains('Partner').click()
  })

  it('renaming a maturity state updates everyone who is at that stage', () => {
    cy.viewport(1280, 720)

    cy.createPerson({ firstName: 'Frodo' })
    cy.dataCy('maturity-selection').click()
    cy.contains(/young Christian/i).click()
    cy.createPerson({ firstName: 'Pippin' })
    cy.dataCy('maturity-selection').click()
    cy.contains(/young Christian/i).click()
    cy.createPerson({ firstName: 'Bilbo' })
    cy.dataCy('maturity-selection').click()
    cy.contains(/mature Christian/i).click()

    cy.dataCy('page-settings').click()
    cy.dataCy('maturity-stages')
      .find('[data-cy=edit-button]')
      .click()
    cy.dataCy('maturity-stage-name').eq(1)
      .clear()
      .type('Youngster')
    cy.dataCy('maturity-done').click()

    cy.dataCy('page-people').click()
    cy.contains('Frodo').click()
    cy.dataCy('maturity-selection').find('input').should('have.value', 'Youngster')
    cy.contains('Pippin').click()
    cy.dataCy('maturity-selection').find('input').should('have.value', 'Youngster')
    cy.contains('Bilbo').click()
    cy.dataCy('maturity-selection').find('input').should('have.value', 'Mature Christian')
  })
})
