export {
  VaultBatchError,
  VaultVersionConflictError,
  addPushSubscription,
  createAccount,
  deletePushSubscription,
  fetchMany,
  getMetadata,
  getReminderSettings,
  getSalt,
  getSession,
  put,
  putMany,
  recordPrayerCompletion,
  setMetadata,
  updateReminderSettings,
} from './vault/client'

export type {
  AccountCreationResponse,
  BatchResultResponse,
  CachedVaultItem,
  CreateAccountBody,
  FetchManyResponse,
  LoginBody,
  ReminderSettingsResponse,
  VaultItem,
  VaultMetadataEnvelope,
} from './vault/client'

export {
  fetchMany as vaultFetchMany,
  put as vaultPut,
  putMany as vaultPutMany,
  createAccount as vaultCreateAccount,
  getSalt as vaultGetSalt,
  getSession as vaultGetSession,
  getMetadata as vaultGetMetadata,
  setMetadata as vaultSetMetadata,
  addPushSubscription as vaultAddPushSubscription,
  deletePushSubscription as vaultDeletePushSubscription,
  getReminderSettings as vaultGetReminderSettings,
  updateReminderSettings as vaultUpdateReminderSettings,
  recordPrayerCompletion as vaultRecordPrayerCompletion,
} from './vault/client'
