version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "."]
    volumes:
      - dynamodata:/home/dynamodblocal

  api:
    image: vault-api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - dynamodb
    volumes:
      - ..:/prm
    ports:
      - 4000:4000
    command: yarn dev

volumes:
  dynamodata:
