/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_VAULT_ENDPOINT: string
  readonly VITE_VAPID_PUBLIC_KEY: string
  readonly VITE_PUBLIC_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}